# Generated by Django 5.0.5 on 2024-05-10 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_fcm_token_alter_forgotpassword_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 5, 34, 0, 148560, tzinfo=datetime.timezone.utc)),
        ),
    ]
