# Generated by Django 5.0.5 on 2024-05-10 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_verification_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='alert',
            name='slug',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 8, 8, 58, 864201, tzinfo=datetime.timezone.utc)),
        ),
    ]
