# Generated by Django 5.0.6 on 2024-07-02 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_alert_name_alter_alert_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 13, 19, 48, 401296, tzinfo=datetime.timezone.utc)),
        ),
    ]
