# Generated by Django 5.0.6 on 2024-07-02 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_imageupload_alter_forgotpassword_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpassword',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 13, 23, 52, 778038, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
